#!/bin/bash
# BACKLOG - Backup SystemLog.txt file to $WINUBUNTU_PATH
#	6/15/21.	wmk.	23:20
# Usage. bash BACKLOG [-n] executed from $HOME/Documents
#
#	-n - optional parameter (anything non-null); if present
#            indicates to backup the log file and start a new one
#
# Entry. $HOME contains the SystemLog.txt file that is a running
# log of system commands and events.
#        $system_log = /home/ubuntu/SystemLog.txt
#
# Exit.	($)system_log copied to ($)WINUBUNTU_PATH if no -n parameter
#		if -n parameter anything non-null then
#		  ($)WINUBUNTU_PATH/SystemLog.txt
#			 copied to ($)WINUBUNTU_PATH/SystemLog~.txt
#		  then ($)system_log copieD to ($)WINUBUNTU_PATH
#
# Modification History.
# ---------------------
# 7/19/20.	wmk.	original code.
# 6/15/21.	wmk.	documentation; code improvements; persistent Ubuntu
#					detection/ignore.
# check if running on persistent system..
if [ "$HOME" != "/home/ubuntu" ]; then
 ~/sysprocs/LOGMSG "  BACKLOG attempted on persistent system - abandoned."
 echo "  BACKLOG attempted on persistent system - abandoned."
 exit 0
fi
if [ -z "$1" ]; then
  cp $system_log $WINUBUNTU_PATH #
  if [ $? -eq 0 ]; then
#    date +%T >> $system_log #
#    echo "  System log backed up to $WINUBUNTU_PATH " >> $system_log #
    ~/sysprocs/LOGMSG "  System log backed up to $WINUBUNTU_PATH "
    echo "System log backed up to $WINUBUNTU_PATH "
  else
#    date +%T >> $system_log #
#    echo "  System log backup FAILED." >> $system_log #
	~/sysprocs/LOGMSG "  System log backup FAILED."
    echo "System log backup FAILED."
  fi
else
  mv $WINUBUNTU_PATH/SystemLog.txt $WINUBUNTU_PATH/SystemLog~.txt
  cp $system_log $WINUBUNTU_PATH #
  if [ $? -eq 0 ]; then
    rm $system_log #
    touch $system_log
#    date > $system_log #
#    echo "  System log backed up and restarted." >> $system_log #
    ~/sysprocs/LOGMSG "  System log backed up and restarted."
    echo "System log backed up and restarted."
  else
#    date +%T >> $system_log #
#    echo "  System log backup FAILED." >> $system_log #
    ~/sysprocs/LOGMSG "  System log backup FAILED."
    echo "System log backup FAILED."
  fi
fi
# end BACKLOG
