#!/bin/bash
# COLDSTART_1 - bash shell to be run after COLDSTART has completed.
#	7/24/20.	wmk.	17:00
# Usage.   bash COLDSTART_1
# Entry. System time set to Eastern time
#	Initialize System Log file
#	System log message issued with date/time stamp 
#	Configuration files copied to $HOME
#	System startup procedures copied to $HOME/startup
#	System bash procedures copied to $HOME/sysprocs
#	Terminal restart advised to pick up configuration files
# Exit. (run COLDSTART_1)
# 	  Touchpad disabled	
#         Universe repository connected
#	  [Special bash files with command aliases copied to $HOME\sysprocs]
#	  Install git
#	  Install Geany
#	  Install Zoom
#	  Install Java JRE/JDK
#	  Install FlowBlade
#	  Install testdisk
#	  Install Python
#	  Remind user to copy WINUBUNTU/.ssh/id_rsa, id_rsa.pub to ~/.ssh
#         and run ssh-agent add to register the current SSH keys
# Modification History.
# --------------------
# 7/21/20. wmk.	original
# 7/23/20. wmk.	added testdisk and Python installs
# 7/24/20. wmk.	eliminated exit at end to save Terminal session; updated
#               script to include SSH key installation and registration
if [ -z $system_log ]; then
  system_log=$HOME/SystemLog.txt
else
  echo "system_log environment var already set."
fi  # end system_log defined conditional
date >> $system_log #
echo "  System COLDSTART_1 initiated." >> $system_log #
echo "  System COLDSTART_1 initiated."
# connect universe repository
date +%T >> $system_log #
echo "  Connecting universe repository..." >> $system_log #
echo "  Connecting universe repository..."
sudo apt update
sudo add-apt-repository universe
# install packages for standard system operations using sysprocs
# and aliases defined in ~/.bashrc
Installgit
InstallGeany
InstallZoom
InstallJRE
InstallFlowBlade
Installtestdisk
InstallPython
date +%T >> $system_log #
echo "  COLDSTART_1 Complete." >> $system_log #
echo "  COLDSTART_1 Complete."

