#!/bin/bash
# COLDSTART - bash shell to be run after hard reset of system.
#	1/31/21.	wmk.	17:30
# Usage.   bash COLDSTART
# Entry. environment var startup_src set in .bashrc
# Exit. System time set to Eastern time
#	Initialize System Log file
#	System log message issued with date/time stamp 
#       Create $TEMP_PATH directory ~/temp
#	Configuration files copied to $HOME
#	System startup procedures copied to $HOME/startup
#	System bash procedures copied to ~/sysprocs
#	Terminal restart advised to pick up configuration files
#	Run COLDSTART_1
# 	  Touchpad disabled	
#         Universe repository connected
#	  Special bash files with command aliases copied to $HOME
#	  Install git
#	  Install Geany
#	  Install Zoom
#	  Install Java JDK
#	  Install FlowBlade
#     Install testdisk
#	  Install Python
#     Install Bless (hex file editor)
#     Install SQL Lite
#     [Install wifi driver]
#	  Remind user to copy WINUBUNTU/.ssh/id_rsa, id_rsa.pub to ~/.ssh
#         and run ssh-agent add to register the current SSH keys
#
# Modification History.
# --------------------
# 7/20/20.	wmk.	original script
# 7/21/20.	wmk.	swapped out terminal_ for term_; testdisk utility
#                       added
# 7/23/20.	wmk.	moved term_, termx_ and SETBACK to $HOME/sysprocs; add
#                       InstallPython to COLDSTART_1 list
# 7/24/20.	wmk.	code added to create $TEMP_PATH directory ~/temp
# 7/30/20.  wmk.    documentation on InstallSQL
# 8/6/20.	wmk.	SQL, ENDSQL added to /sysprocs copy
# 1/30/21.  wmk.	2ys, nyes, yes prompt input files added; UNLOAD,
#					InstallTPadI added
# 2/11/21.	wmk.	log messages consolidated with date/time stamp.
timedatectl set-timezone America/New_York #
if [ -z $system_log ]; then
  system_log=$HOME/SystemLog.txt
else
  echo "system_log environment var already set."
fi  # end system_log defined conditional
touch $system_log #
date +%F.%H.%M.%S | sed 's/$/ System COLDSTART initiated. &/' >> $system_log #
#echo "  System COLDSTART initiated." >> $system_log #
echo "  System COLDSTART initiated."
# create $TEMP_PATH directory
mkdir ~/temp
# copy configuration files to $HOME
#date +%T >> $system_log #
date +%H.%M.%S | sed 's/$/  Copying configuration files... &/'  >> $system_log #
echo "  Copying configuration files..." >> $system_log #
echo "  Copying configuration files..."
cd $HOME
startup_src=/media/ubuntu/Windows/Users/Bill/ubuntu/sysstart
cp $startup_src/.bashrc ./
cp $startup_src/.gitconfig ./
cp $startup_src/SYSEDIT ./
# copy startup shells to $HOME/sysstart
cd $HOME
if  cd ./sysstart ; then
 date +%T >> $system_log #
 echo "  ~/sysstart already in place" >> $system_log #
 echo "  ~/sysstart already in place"
 cd ..
else
 mkdir sysstart
 date +%T  | sed 's/$/  Creating ~/sysstart... &/' >> $system_log #
 echo "  Creating ~/sysstart.." >> $system_log
 echo "  Creating ~/sysstart.."
 cp $startup_src/COLDSTART ./sysstart
 cp $startup_src/COLDSTART_1 ./sysstart
 cp $startup_src/QUICKSTART ./sysstart
 cp $startup_src/WARMSTART ./sysstart
 cp $startup_src/SYSEDIT ./sysstart
fi  # end $HOME/sysstart exists conditional
# copy sysprocs shells to $HOME/sysprocs
if cd ./sysprocs ; then
 date +%T | sed 's/$/  ~\/sysprocs already in place &/' >> $system_log #
 echo "  ~/sysprocs already in place" >> $system_log #
 echo "  ~/sysprocs already in place"
 cd ..
else
 mkdir sysprocs
 date +%T >> $system_log #
 echo "  Creating ~/sysprocs.." >> $system_log #
 echo "  Creating ~/sysprocs.."
sysproc_src=/media/ubuntu/Windows/Users/Bill/ubuntu/sysprocs
 cp $startup_src/term_ ./sysprocs
 cp $startup_src/termx_ ./sysprocs
 cp $sysproc_src/KillTPad.sh ./sysprocs
 cp $sysproc_src/EnblTPad.sh ./sysprocs
 cp $sysproc_src/Installgit.sh ./sysprocs
 cp $sysproc_src/InstallGeany.sh ./sysprocs
 cp $sysproc_src/InstallJRE.sh ./sysprocs
 cp $sysproc_src/InstallSQLite.sh ./sysprocs
 cp $sysproc_src/PJDUMP ./sysprocs
 cp $sysproc_src/PF-Utilities-README.txt ./sysprocs
 cp $sysproc_src/InstallZoom.sh ./sysprocs
 cp $sysproc_src/InstallFlowBlade.sh ./sysprocs
 cp $sysproc_src/SYSEDIT ./sysprocs
 cp $sysproc_src/SETBACK ./sysprocs
 cp $sysproc_src/EJECT ./sysprocs
 cp $sysproc_src/LISTENV ./sysprocs
 cp $sysproc_src/Installtestdisk.sh ./sysprocs
 cp $sysproc_src/PSFIND ./sysprocs
 cp $sysproc_src/SQL ./sysprocs
 cp $sysproc_src/ENDSQL ./sysprocs
 cp $sysproc_src/UNLOAD ./sysprocs
 cp $sysproc_src/InstallTPadI.sh ./sysprocs
 cp $sysproc_src/sysedits.sh ./sysprocs
fi  # end $HOME/sysprocs exists conditional
 date +%T >> $system_log #
 echo "" > nyes
 echo "y" >> nyes
 echo "y" > 2ys
 echo "y" >> 2ys
 echo "y" > yes
 echo "" >> yes
 echo "  COLDSTART complete." >> $system_log #
 echo "  COLDSTART complete."
# advise terminal restart and run COLDSTART_1
echo "Exit Terminal then restart Terminal to run COLDSTART_1"
