#!/bin/bash
# LOGMSG - Set message string in system log.
#	9/28/20.  wmk.  08:30
# Usage. bash LOGMSG [options] "<message-text>"
#	[options] utility options - see Notes.
#	<message-text> message to be issued to system log
#   adapted from SETMSG
#
# Modification History.
# ---------------------
# 9/28/20.	wmk.	original shell
# 11/13/20.	wmk.	-q option added; jumpto definition added
# Notes. options -q or -Q	quiet mode; no echo of message
# jumpto function definition
function jumpto
{
    label=$1
    cmd=$(sed -n "/$label:/{:a;n;p;ba};" $0 | grep -v ':$')
    eval "$cmd"
    exit
}
date +%T >> $system_log #
if [ -z "$2" ]; then
 if [ -z "$1" ]; then
  if [ "$1" == "-q" ] || [ $1 == "-Q" ]; then
   echo "  <>." >> $system_log #
   echo "  time-stamp issued to system log."
  fi
 echo "  $1" >> $system_log #
 echo "  System log entry made. "
 fi
else
 if [ "$1" == "-q" ] || [ "" == "-Q" ]; then
  if [ -z "$2" ]; then
   echo "  <>." >> $system_log #
   echo "  time-stamp issued to system log."
  else
   echo "  $2" >> $system_log #
  fi
 else
    echo "unrecognized option '$1'"
    jumpto alldone
 fi
fi
jumpto alldone
alldone:
