#!/bin/bash
# LOGMSG - Set message string in system log.
#	5/27/21.  wmk.  6:57
# Usage. bash LOGMSG [options] "<message-text>"
#	[options] utility options - see Notes.
#	<message-text> message to be issued to system log
#   adapted from SETMSG
#
# Modification History.
# ---------------------
# 9/28/20.	wmk.	original shell
# 11/13/20.	wmk.	-q option added; jumpto definition added
# 2/11/21.	wmk.	code overhaul to combine timestamp with message.
# 3/1/21.	wmk.	fix environment vars when called from make.
# 5/27/21.	wmk.	add code to set folderbase given system; modified
#					for use with Kay's system.
# 6/16/21.	wmk.	multihost support improved.
# Notes. options -q or -Q	quiet mode; no echo of message
# jumpto function definition
function jumpto
{
    label=$1
    cmd=$(sed -n "/$label:/{:a;n;p;ba};" $0 | grep -v ':$')
    eval "$cmd"
    exit
}
if [ "$HOME" = "/home/ubuntu" ]; then
 folderbase="/media/ubuntu/Windows/Users/Bill"
else 
 folderbase=$HOME
fi
if [ -z "$system_log" ]; then
  system_log="$folderbase/ubuntu/SystemLog.txt"
fi
OPTION=$1
MSG=$2
if [ -z "$MSG" ] && [ -z "$OPTION" ]; then
 MSG="<.>."
 echo "  time-stamp issued to system log."
 jumpto IssueMsg
fi
if [ -z "$MSG" ]; then
 MSG=$OPTION
 if [ not = ${#OPTION}  ]; then
  if [ "$OPTION" == "-q" ] || [ "$OPTION" == "-Q" ]; then
#   date +%T >> $system_log #
#   echo "  <>." >> $system_log #
   bash ~/sysprocs/LOGMSG "  <>." 
#   echo "  time-stamp issued to system log."
  else
   echo "  System log entry made. "
  fi
 # echo "  $MSG" >> $system_log #
 jumpto IssueMsg
 fi
else   # 2 parameters...
 if [ "$OPTION" == "-q" ] || [ "$OPTION" == "-Q" ]; then
  if [ -z "$MSG" ]; then
   MSG="  <>."
#   echo "  <>." >> $system_log #
#   bash ~/sysprocs/LOGMSG "  <>." 
   echo "  time-stamp issued to system log."
   jumpto IssueMsg
  fi

 else
    echo "unrecognized option '$OPTION'"
    jumpto alldone
 fi
fi

jumpto IssueMsg
IssueMsg:
pushd ./ >junk.txt
cd ~/Documents
date +%H.%M.%S. >logmsg.sh
echo "$MSG \" " >> logmsg.sh
echo ">> \$system_log #" >>logmsg.sh
sed -i -n ':a;$!N;s/\n//;ta;P;D'  logmsg.sh
sed -i 's/./echo -e \"&/' logmsg.sh
. logmsg.sh
popd >junk.txt


jumpto alldone
alldone:
# end LOGMSG
