#!/bin/bash
# NewSYSEDIT - Replace current ~/sysprocs/SYSEDIT with new version.
#	6/15/21.	wmk.  22:25
#
#	Entry.	($)WINGIT_PATH = folder path of GitHub on Windows drive.
#
#	Exit. ~/sysprocs/SYSEDIT replaced with new version from GitHub.
#		  ~/sysstart/SYSEDIT replaced with new version from GitHub.
#
# Modification History.
# --------------------
# 7/21/20.  wmk.	original script.
# 7/24/20.  wmk.	added code to also copy to WINUBUNTU/sysprocs bash.
# 2/13/21.	wmk.	one-line log messages; LOGMSG.
# 6/15/21.	wmk.	multihost support; code improvements; /sysstart
#					version also replaced.
#date +%T >> $system_log #
#echo "  NewSYSEDIT initiated." >> $system_log #
bash ~/sysprocs/LOGMSG "  NewSYSEDIT initiated."
echo "NewSYSEDIT will overwrite the current ~/sysprocs/SYSEDIT"
read -p "Do you wish to continue (y/n)? "
P1=${REPLY,,}
if [ "$P1" == 'y' ] ; then
#  date +%T >> $system_log #
#  echo "  updating ~/sysprocs/SYSEDIT..." >> $system_log #
  bash ~/sysprocs/LOGMSG "  updating ~/sysprocs/SYSEDIT..."
  echo "  updating ~/sysprocs/SYSEDIT..."
  cp -u $WINGIT_PATH/ShellFiles/SYSEDIT ~/sysprocs/SYSEDIT #
  echo "  updating ~/sysstart/SYSEDIT..."
  cp -u $WINGIT_PATH/ShellFiles/SYSEDIT ~/sysstart/SYSEDIT #
#  echo "  updating WINUBUNTU_PATH/sysprocs/SYSEDIT..." >> $system_log #
  bash ~/sysprocs/LOGMSG "  updating WINUBUNTU_PATH/sysprocs/SYSEDIT..."
  echo "  updating $WINUBUNTU_PATH/sysprocs/SYSEDIT..."
  cp -u $WINGIT_PATH/ShellFiles/SYSEDIT $WINUBUNTU_PATH/sysprocs/SYSEDIT #
  echo "  updating $WINUBUNTU_PATH/sysstart/SYSEDIT..."
  cp -u $WINGIT_PATH/ShellFiles/SYSEDIT $WINUBUNTU_PATH/sysstart/SYSEDIT #
#  date +%T >> $system_log #
#  echo "  NewSYSEDIT complete." >> $system_log #
  bash ~/sysprocs/LOGMSG "  NewSYSEDIT complete."
  echo "  NewSYSEDIT complete."
else
#  date +%T >> $system_log #
#  echo "  NewSYSEDIT abandoned at user request." >> $system_log #
  bash ~/sysprocs/LOGMSG "  NewSYSEDIT abandoned at user request."
  echo "  NewSYSEDIT abandoned at user request."
fi  # end user ok with overwrite conditional
# end NewSYSEDIT
