#!/bin/bash
#PFLOAD - emulate incremental Cyber PFLOAD using predetermined directory names.
#  7/15/20.  11:00 NEEDS TO BE REWRITTEN TO BRING PROJECT BACK TO /Windows/../StagingArea-In
#                   FROM ../USB20FD/git-Projects
# Because of the volatility of ubuntu non-persistent, and the risk of unexpected crashes
# git Projects will only be modifie on the Windows hard-drive. This stands the best chance
# of not losing local changes.
# If the local project on the /Windows/ hard drive is corrupted, this will provide two
# options: 1) delete the Project on the /Windows hard drive and use PFLOAD to do a full
# reload, then PFDESTAGE to clone it back from the StagingArea-In, or 2) use
# "git clone origin <project-name>" to re-clone from the last push to GitHub.
echo -e "PFLOAD Initiated..\nSource = /media/ubuntu/USB20FD/StagingArea-In/PNY-StagingArea-In"
echo -e "Destination = /media/ubuntu/USB20FD"
read -p "Proceed with PFLOAD? (y/n)"
if [ $REPLY == 'y' ] || [ $REPLY == 'Y' ]; then
  echo "PFLOAD proceeding..."
else
  echo "PFLOAD Abandoned at user request."
  exit 0
fi
# verify both paths exist
PFLOAD_SOURCE='/media/ubuntu/USB20FD/StagingArea-In/PNY-StagingArea-In'
PFLOAD_DEST='/media/ubuntu/USB20FD'
if  cd $PFLOAD_SOURCE ; then
 echo
else
 echo -e "Source path '"$PFLOAD_SOURCE"' not found.\nPFLOAD Abandoned."
 exit 1
fi
if cd $PFLOAD_DEST ; then
 echo
else
  echo  -e"Destination path '"$PFLOAD_DEST"' not found.\nPFLOAD Abandoned."
  exit 1
fi
# proceed with PFLOAD
echo "Stubbed.. copy -r -u -t would execute here.."
echo "PFLOAD complete."
exit 0




