#!/bin/bash
# QUICKSTART - abbreviated system startup only installing Zoom.
#	7/23/20.	wmk.	12:30
# Usage. bash QUICKSTART
# Exit.  key initializations performed; bare bones ubuntu runnning
#	System time set to Eastern time
#	Initialize System Log file
#	System log message issued with date/time stamp 
#	Configuration files copied to $HOME
#	System startup procedures copied to $HOME/startup
#	System bash procedures copied to $HOME/sysprocs
#       Universe repository connected
#	Special bash files with command aliases copied to ~/sysprocs
#       Zoom app installed and available
# Modification History.
# --------------------
# 7/23/20.	wmk.	moved term_ and termx_ to /sysprocs; added
#                       Installtestdisk and InstallPython to /sysprocs
timedatectl set-timezone America/New_York #
if [ -z $system_log ]; then
  system_log=$HOME/SystemLog.txt
else
  echo "system_log environment var already set."
fi  # end system_log defined conditional
touch $system_log #
date >> $system_log #
echo "  System QUICKSTART initiated." >> $system_log #
echo "  System QUICKSTART initiated."
echo "  Terminal started." >> $system_log #
# copy configuration files to $HOME
date +%T >> $system_log #
echo "  Copying configuration files..." >> $system_log #
echo "  Copying configuration files..."
cd $HOME
startup_src=/media/ubuntu/Windows/Users/Bill/ubuntu/sysstart
cp $startup_src/.bashrc ./
cp $startup_src/.gitconfig ./
# copy startup shells to $HOME/sysstart
cd $HOME
if  cd ./sysstart ; then
 date +%T >> $system_log #
 echo "  ~/sysstart already in place" >> $system_log #
 echo "  ~/sysstart already in place"
 cd ..
else
 mkdir sysstart
 date +%T >> $system_log #
 echo "  Creating ~/sysstart.." >> $system_log
 echo "  Creating ~/sysstart.."
 cp $startup_src/COLDSTART ./sysstart
 cp $startup_src/COLDSTART_1 ./sysstart
 cp $startup_src/QUICKSTART ./sysstart
 cp $startup_src/WARMSTART ./sysstart
fi  # end $HOME/sysstart exists conditional
# copy sysprocs shells to $HOME/sysprocs
if cd ./sysprocs ; then
 date +%T >> $system_log #
 echo "  ~/sysprocs already in place" >> $system_log #
 echo "  ~/sysprocs already in place"
 cd ..
else
 mkdir sysprocs
 date +%T >> $system_log #
 echo "  Creating ~/sysprocs.." >> $system_log #
 echo "  Creating ~/sysprocs.."
sysproc_src=/media/ubuntu/Windows/Users/Bill/ubuntu/sysprocs
 cp $sysproc_src/terminal_ ./
 cp $sysproc_src/termx_ ./
 cp $sysproc_src/KillTPad.sh ./sysprocs
 cp $sysproc_src/EnblTPad.sh ./sysprocs
 cp $sysproc_src/Installgit.sh ./sysprocs
 cp $sysproc_src/InstallGeany.sh ./sysprocs
 cp $sysproc_src/InstallJRE.sh ./sysprocs
 cp $sysproc_src/PJDUMP ./sysprocs
 cp $sysproc_src/SETBACK ./sysprocs
 cp $sysproc_src/PF-Utilities-README.txt ./sysprocs
 cp $sysproc_src/InstallZoom.sh ./sysprocs
 cp $sysproc_src/InstallFlowBlade.sh ./sysprocs
 cp $sysproc_src/Installtestdisk.sh ./sysprocs
 cp $sysproc_src/InstallPython.sh ./sysprocs
fi  # end $HOME/sysprocs exists conditional
# install Zoom
bash ~/sysprocs/InstallZoom.sh
date +%T >> $system_log #
echo "  QUICKSTART complete." >> $system_log #
echo "  COLDSTART complete."
exit 0
