#!/bin/bash
# SETMSG - Set message string for next Terminal startup.
#	12/28/20.  wmk.  09:00
# Usage. bash SETMSG "<message-text>"
#	<message-text> message to be issued next time term_ is used
#   to start a Terminal session.
# Note. 8/5/20 moved to persistent storage.
# 12/25/20. touch added after message cleared.
# 12/27/20. -c parameter added to clear existing message(s) before adding.
# 12/28/20. bug fix at line 18, needed quotes around dollar1.
#if [ len($1) -eq 0 ]; then
if [ -z "$1" ]; then
 touch $WINUBUNTU_PATH/term_user_msg.txt
 rm $WINUBUNTU_PATH/term_user_msg.txt
 touch $WINUBUNTU_PATH/term_user_msg.txt
 date +%T >> $system_log #
 echo "  Terminal startup message cleared." >> $system_log #
 echo "  Terminal startup message cleared."
elif [ "$1" == "-c" ]; then
 touch $WINUBUNTU_PATH/term_user_msg.txt
 rm $WINUBUNTU_PATH/term_user_msg.txt
 touch $WINUBUNTU_PATH/term_user_msg.txt
 date +%T >> $system_log #
 echo "  Terminal startup message cleared." >> $system_log #
 if [ -z "$2" ]; then
  echo "  Terminal startup message cleared."
 else
  echo "$2" >> $WINUBUNTU_PATH/term_user_msg.txt
  echo "  Terminal startup message set. " >> $system_log #
  echo "  Message = \"$1\" " >> $system_log #
  echo "  Terminal startup message set. "
 fi
else
 echo "$1" >> $WINUBUNTU_PATH/term_user_msg.txt
 echo "  Terminal startup message set. " >> $system_log #
 echo "  Message = \"$1\" " >> $system_log #
 echo "  Terminal startup message set. "
fi
