#!/bin/bash
#SQL - Start sqlite3 with optional db specification
#	8/6/20.	wmk.	12:00
date +%T >> $system_log #
echo "  Starting sqlite3 session." >> $system_log #
echo "Running sqlite3..."
sqlite3 $1
echo "Enter ENDSQL to log end of SQL session..."
