#!/bin/bash
# term_ - standard terminal starup bash script.
#	2/14/21.	wmk.	01:45
# Usage. bash terminal_ <option>
#	<option> = if present, list environment variables from .bashrc
#
# Entry. alias terminal_='bash $HOME/terminal_' defined in $HOME/.bashrc
#	U_DISK = /media/ubuntu
#	PJ_BACK = 'git-Projects
#	WINGIT_PATH = /media/ubuntu/Windows/Users/Bill/Documents/GitHub
#	WINUBUNTU_PATH = /media/ubuntu/Windows/Users/Bill/ubuntu
# Modification History.
# --------------------
# 7/??/20.  wmk.	original script
# 7/24/29.  wmk.	modified to display ~/term_user_msg.txt if it exists;
#                       this allows for a reminder text to be saved and displayed
#                       the next time term_ starts up.
# 8/5/20.	wmk.	get term_user_msg.txt from persistent storage.
# 2/12/21.	wmk.	LOGMSG used to message to system_log.
# 2/14/21.	wmk.	bu_ environment var set /media/ubuntu/Windows/StagingAreaIn
# 2/21/21.	wmk.	LOGMSG direct calls failed; use sysprocs path.
# Notes.
# By entering the "term_" command, the user makes a $system_log entry
# with the time stamp of when the bash session was started. [If a parameter
# is included, it will be a quoted literal that will also be recorded in
# the $system_log.] If the file ~/term_user_msg.txt exists, it will be displayed.
#date +%T >> $system_log #
#echo "  Terminal app started." >> $system_log #
bash ~/sysprocs/LOGMSG "  Terminal app started."
bu_="/media/ubuntu/Windows/StagingAreaIn"
if [ -z $1 ]; then
  echo "Terminal app started."
else
  echo "Terminal app started."
  echo "  U_DISK = '$U_DISK'"
  echo "  WINGIT_PATH = '$WINGIT_PATH'"
  echo "  BACKUP_PATH = '$BACKUP_PATH'"
  echo "  PJ_BACK = '$PJ_BACK'"
  echo "  WINUBUNTU_PATH = 'WINUBUNTU_PATH'"
  echo "  TEMP_PATH = '$HOME/temp'"
  echo "  system_log = '$system_log'"
#  echo "  .bashsrc environment vars displayed." >> $system_log #
  bash ~/sysprocs/LOGMSG "  .bashsrc environment vars displayed."
fi
touch $WINUBUNTU_PATH/term_user_msg.txt
 cat $WINUBUNTU_PATH/term_user_msg.txt
