#!/bin/bash
# WARMSTART - abbreviated system startup following QUICKSTART.
#	7/27/20.	wmk.	11:45
# Usage. bash WARMSTART
# Entry. QUICKSTART already run
#       key initializations performed; bare bones ubuntu runnning
#	System time set to Eastern time
#	Initialize System Log file
#	System log message issued with date/time stamp 
#	Configuration files copied to $HOME
#	System startup procedures copied to $HOME/sysstart
#	System bash procedures copied to $HOME/sysprocs
#       Universe repository connected
#	Special bash files with command aliases copied to ~/sysprocs
#       Zoom app installed and available
# WARMSTART - complete startup where QUICKSTART left off.
# Exit.
#	Touchpad disabled
#	Install git
#	Install Geany
#	Install Java JDK/JDR
#	Install FlowBlade
#   Install testdisk
#	Install Python
#	InstallBless
#	InstallSQL
#	InstallWifi
#	[SYSEDIT LibreCalc to include BadAss, XRay and Standard/Module1 with DayName]
# Modification History.
# --------------------
# 7/24/20.	wmk.	original script
# 7/27/20.	wmk.	InstallBless, InstallSQL, InstallWifi added
date +%T >> $system_log
echo "  WARMSTART initiated..."  >> $system_log #
echo "  WARMSTART initiated..."
KillTPad
Installgit
InstallGeany
InstallJDK
InstallFlowBlade
Installtestdisk
InstallPython
InstallBless
InstallSQL
InstallWifi
date +%T >> $system_log
echo "  WARMSTART complete."  >> $system_log #
echo "  WARMSTART complete."



