#!/bin/bash
# WARMSTART - abbreviated system startup following QUICKSTART.
#	7/21/20.	wmk.	16:15
# Usage. bash WARMSTART
# Entry. QUICKSTART already run
#       key initializations performed; bare bones ubuntu runnning
#	System time set to Eastern time
#	Initialize System Log file
#	System log message issued with date/time stamp 
#	Configuration files copied to $HOME
#	System startup procedures copied to $HOME/sysstart
#	System bash procedures copied to $HOME/sysprocs
#       Universe repository connected
#	Special bash files with command aliases copied to ~/sysprocs
#       Zoom app installed and available
# WARMSTART - complete startup where QUICKSTART left off.
# Exit.
#	Touchpad disabled
#	Install git
#	Install Geany
#	Install Java JDK/JDR
#	Install FlowBlade
#       Install testdisk
#	Install Python
#	[SYSEDIT LibreCalc to include BadAss, XRay and Standard/Module1 with DayName]
date +%T >> $system_log
echo "  WARMSTART initiated..."  >> $system_log #
echo "  WARMSTART initiated..."
KillTPad
Installgit
InstallGeany
InstallJDK
InstallFlowBlade
Installtestdisk
InstallPython
date +%T >> $system_log
echo "  WARMSTART complete."  >> $system_log #
echo "  WARMSTART complete."



